spring.config.import=optional:file:/config/customer_config.yml
spring.datasource.url=${db_url}
spring.datasource.jdbcurl=${db_url}
spring.datasource.username=${db_user}
spring.datasource.password=${db_password}
spring.datasource.pool-size=${db_poolsize}
