spring.config.import=file:../config/customer_config.yml
app.datasource.jdbcurl=${db_url}
app.datasource.username=${db_user}
app.datasource.password=${db_password}
app.datasource.pool-size=${db_poolsize}
